---
title: "Project Proposal"
author: "Jiner Zheng"
date: "10/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
library(dplyr)
library(readr)

library(tsbox)
#excess_death <- read.csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/excess-deaths/deaths.csv")
url = "https://raw.githubusercontent.com/akarlinsky/world_mortality/main/world_mortality.csv"
excess_death <- read_csv(url(url))
us_death <- excess_death %>% 
  filter(country_name=="United States")
brazil_death <- excess_death %>% 
  filter(country_name=="Brazil")
russia_death <- excess_death %>% 
  filter(country_name=="Russia")
uk_death <- excess_death %>% 
  filter(country_name=="United Kingdom")
us_ts <- ts(us_death$deaths, frequency = 52,start = c(2015,2))
uk_ts <- ts(uk_death$deaths, frequency = 52,start = c(2015,1))
brazil_ts <- ts(brazil_death$deaths, frequency = 12,start = c(2015,1))
russia_ts <- ts(russia_death$deaths, frequency = 12,start = c(2015,1))
ts.plot(us_ts,ylab="Weekly Deaths from all causes in US")
ts.plot(uk_ts, ylab="Weekly Deaths from all causes in UK")
ts.plot(brazil_ts,ylab="Monthly Deaths from all causes in Brazil")
ts.plot(russia_ts,ylab="Monthly Deaths from all causes in Russia")
```
```{r}
plot(decompose(us_ts))
plot(decompose(uk_ts))
plot(decompose(brazil_ts))
plot(decompose(russia_ts))
```

```{r correlogram}
acf(uk_ts, plot = TRUE, main = "UK deaths Correlogram")
acf(us_ts, plot = TRUE, main = "US deaths Correlogram")
acf(brazil_ts, plot = TRUE, main = "Brazil deaths Correlogram")
acf(russia_ts, plot = TRUE, main = "Russia deaths Correlogram")
```

